---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: av-linux
description: SeaGL Aviary Linux

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 42

modules:
  - type: rpm-ostree
    install:
      # General system packages
      - jq
      - age
      - seahorse
      - gedit
      # Streaming machine packages
      - obs-studio
      - obs-studio-plugin-vaapi
      - obs-studio-devel # TODO figure out how to remove this, it's needed to build OBS Source Record
      - cmake # Ditto
      - gcc-c++ # Ditto
      - mpv
      - yt-dlp
      - zenity
      - rclone
      - fuse-devel
      - cheese
      - nodejs
      - dbus-x11 # Without this, gsettings errors out trying to spawn `dbus-launch`
      # Presentation machine packages
      - libreoffice
      - nextcloud-client
      - nextcloud-client-nautilus
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/tarulia/obs-studio-plugins/repo/fedora-%OS_VERSION%/tarulia-obs-studio-plugins-fedora-%OS_VERSION%.repo
    install:
      - obs-studio-plugin-advanced-scene-switcher
  - type: script
    snippets:
      - cd /tmp &&
        git clone --branch 0.4.6 https://github.com/exeldro/obs-source-record.git &&
        cd obs-source-record/ &&
        cmake -S . -B build -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_OUT_OF_TREE=On && cmake --build build &&
        cd build &&
        sudo make install &&
        sudo mv /usr/lib/obs-plugins/source-record.so /usr/lib64/obs-plugins # TODO figure out how to not do this
  # This is early and targeted so that we can install Zrok in lower layers,
  # but not invalidate larger lower layers whenever anything in /etc changes
  - type: files
    files:
      - source: etc/yum.repos.d
        destination: /etc/yum.repos.d
  - type: rpm-ostree
    # repos:
    #   - https://packages.openziti.org/zitipax-openziti-rpm-stable/redhat/x86_64/
    keys:
      - https://packages.openziti.org/zitipax-openziti-rpm-stable/redhat/x86_64/repodata/repomd.xml.key
    install:
      - zrok
    optfix:
      - openziti
  - type: gnome-extensions
    install:
      - 6433 # App menu is back
      - 5410 # Grand Theft Focus
  - type: gschema-overrides
    include:
      - zz1-disable-gnome-shell-animations.gschema.override
      - zz1-disable-screen-lock.gschema.override
      - zz1-gnome-shell-extensions.gschema.override
      - zz1-set-gnome-shell-dock.gschema.override
      - zz1-suppress-autosuspend.gschema.override
  - type: containerfile
    snippets:
      - >
        RUN --mount=type=bind,src=apps/aviaryui,dst=/tmp/aviaryui
        cd /tmp/aviaryui &&
        rpm-ostree install meson cmake glib2-devel gtk4-devel &&
        meson setup /tmp/aviaryui-meson --prefix=/usr &&
        meson compile -C /tmp/aviaryui-meson/ &&
        meson install -C /tmp/aviaryui-meson 
        # TODO figure out how to rip these build deps out of the final image
        # rpm-ostree uninstall meson cmake glib2-devel gtk4-devel
  - type: containerfile
    snippets:
      # XXX figure out why, without --no-bin-links, npm throws EROFS on chmod() on index.js... which SEEMINGLY is actually the creation of a symlink?
      # Except manually creating the symlink works just fine...?
      - RUN --mount=type=bind,src=apps/birdhoused,dst=/tmp/birdhoused cd /tmp/birdhoused && npm --no-bin-links --prefix=/usr install -g --install-links --omit=dev . && ln -s /usr/lib/node_modules/birdhouse-client/index.js /usr/bin/birdhoused && rm -rf /root/.npm
  - type: files
    files:
      - source: usr
        destination: /usr
      - source: etc
        destination: /etc
      # TODO lol should this just use the above directory? I didn't because then it makes the dir hidden in the development repo filesystem...
      - source: home-config
        destination: /etc/skel/.config
  - type: os-release
    properties:
      ID: seaglav
      ID_LIKE: fedora
      NAME: SeaGL Aviary Linux
      PRETTY_NAME: SeaGL Avian Linux 2025 (FROM Fedora Silverblue 42)
      CODE_NAME: '2025'

      IMAGE_VENDOR: SeaGL
      IMAGE_NAME: av-linux
      IMAGE_LIKE: fedora

      HOME_URL: https://github.com/SeaGL/av-linux
      DOCUMENTATION_URL: https://github.com/SeaGL/av-linux/blob/main/README.md
      SUPPORT_URL: https://seagl.org/chat
      BUG_SUPPORT_URL: https://github.com/SeaGL/av-linux/issues
      LOGO_ICON: seagl-logo-icon
      # TODO LOGO_COLOR
  - type: containerfile
    containerfiles:
      - main

  - type: signing

