---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: av-linux
description: SeaGL Aviary Linux

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 42

modules:
  - type: containerfile
    containerfiles:
      - main

  - type: signing

