---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: av-linux
description: SeaGL Aviary Linux

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 42

modules:
  - type: rpm-ostree
    install:
      # General system packages
      - jq
      - age
      - seahorse
      - gedit
      # Streaming machine packages
      - mpv
      - yt-dlp
      - zenity
      - rclone
      - fuse-devel
      - cheese
      # Presentation machine packages
      - libreoffice
      - nextcloud-client
      - nextcloud-client-nautilus
  - type: gnome-extensions
    install:
      - 6433 # App menu is back
      - 5410 # Grand Theft Focus
  - type: gschema-overrides
    include:
      - zz1-disable-gnome-shell-animations.gschema.override
      - zz1-disable-screen-lock.gschema.override
      - zz1-gnome-shell-extensions.gschema.override
      - zz1-set-gnome-shell-dock.gschema.override
      - zz1-suppress-autosuspend.gschema.override
  - type: files
    files:
      - source: usr
        destination: /usr
      - source: etc
        destination: /etc
      # TODO lol should this just use the above directory? I didn't because then it makes the dir hidden in the development repo filesystem...
      - source: home-var-app
        destination: /etc/skel/.var/app
  - type: os-release
    properties:
      ID: seaglav
      ID_LIKE: fedora
      NAME: SeaGL Aviary Linux
      PRETTY_NAME: SeaGL Avian Linux 2025 (FROM Fedora Silverblue 42)
      CODE_NAME: '2025'

      IMAGE_VENDOR: SeaGL
      IMAGE_NAME: av-linux
      IMAGE_LIKE: fedora

      HOME_URL: https://github.com/SeaGL/av-linux
      DOCUMENTATION_URL: https://github.com/SeaGL/av-linux/blob/main/README.md
      SUPPORT_URL: https://seagl.org/chat
      BUG_SUPPORT_URL: https://github.com/SeaGL/av-linux/issues
      LOGO_ICON: seagl-logo-icon
      # TODO LOGO_COLOR
  - type: containerfile
    containerfiles:
      - main

  - type: signing

