---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: av-linux
description: SeaGL Aviary Linux

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 42

modules:
  - type: rpm-ostree
    install:
      # General system packages
      - jq
      - age
      - seahorse
      - gedit
      # Streaming machine packages
      - mpv
      - yt-dlp
      - zenity
      - rclone
      - fuse-devel
      - cheese
      # Presentation machine packages
      - libreoffice
      - nextcloud-client
      - nextcloud-client-nautilus
  - type: containerfile
    containerfiles:
      - main

  - type: signing

