---
name: Lint
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build_push:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Lint
        run: |
          ./lint.sh
